# Site settings
title: Direct Air Capture of CO2 with Moisture Swing Sorbents 
email: co2sorbent@gmail.com
url: https://captureCO2.github.io
description: "Moisture Swing Sorbents: a viable solution for Direct Air Capture of Carbon Dioxide"

# Contact form: comment the line below if you want to stick with the default PHP contact form
contact: static

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: 011f4b #80B3FF dark blue 
  secondary: 6497b1 #FD6E8A 
  secondary-dark: 011f4b #233140 #A2122F

# Footer settings
footer:
  copyright: Kadie Jaffe, Peter Lobaccaro, Martin Gelenter, Tim Sennott
  location: UCB College of Chemistry 
  social: Connect With Us 
  credits: References

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: linkedin
    url: https://www.linkedin.com/pub/kadie-jaffe/91/657/a1a
  - title: github
    url: https://github.com/kadie16
  - title: facebook
    url: https://www.facebook.com/UCBerkeley
  - title: github
    url: https://github.com/captureCO2/captureCO2.github.io

# Postal address (add as many lines as necessary)
address:
  - line: 420 Latimer Hall 
  - line: University of California 
  - line: Berkeley, CA 94720

# Credits content
credits: ' See Spread the Word Section '


# Build settings
markdown: kramdown
permalink: pretty
