# Site settings
title: Direct Air Capture of CO2 with Moisture Swing Sorbents 
email: co2sorbent@gmail.com
url: https://captureCO2.github.io
description: "Moisture Swing Sorbents: a viable solution for Direct Air Capture of Carbon Dioxide"

# Contact form: comment the line below if you want to stick with the default PHP contact form
contact: static

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: 011f4b #80B3FF dark blue 
  secondary: 6497b1 #FD6E8A 
  secondary-dark: 011f4b #233140 #A2122F

# Footer settings
footer:
  copyright: Kadie Jaffe, Peter Lobaccaro, Martin Gelenter, Tim Sennott
  location: Location
  social: Contributors (? We can change title of this)
  credits: References

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: linkedin
    url: http://linkedin.com
  - title: linkedin
    url: http://linkedin.com
  - title: stack-overflow
    url: http://stackoverflow.com/questions/tagged/jekyll
  - title: facebook
    url: http://facebook.com 
  - title: github
    url: http://github.com/jekyll

# Postal address (add as many lines as necessary)
address:
  - line: 420 Latimer Hall 
  - line: University of California 
  - line: Berkeley, CA 94720

# Credits content
credits: 'We can put references here? Links to the papers/where we got figures. For the social section we can put all of our linkedin profiles lol'

# Build settings
markdown: kramdown
permalink: pretty
